/*
 * topics.cpp
 *
 *  Created on: 09.06.2021
 *      Author: Cedric Boes
 */

#include "topics.h"

Topic<uint8_t> TOPICS::SYSTEM_STATE_TOPIC(20, "SYSTEM_STATE_T");

Topic<uint64_t> TOPICS::SIGNAL_INTERVAL_TOPIC(30, "SIGNAL_INTERVAL_T");
Topic<uint64_t> TOPICS::TELEMETRY_INTERVAL_TOPIC(31, "TELEMETRY_INTERVAL_T");

Topic<INTERNAL_MSG::CALIBRATION> TOPICS::CURRENT_CAL_TOPIC(40, "CALIBRATION_T");
Topic<INTERNAL_MSG::MEASUREMENT> TOPICS::CURRENT_DAT_TOPIC(41, "MEASUREMENT_T");

Topic<TELEMETRY::TELEMETRY_MSG> TOPICS::TELEMETRY_TOPIC(50, "TELEMETRY_MSG_T");
Topic<TELECOMMAND::TELECOMMAND_MSG> TOPICS::TELECOMMAND_TOPIC(51, "TELECOMMAND_MSG_T");
