/*
 * lsm9ds1.cpp
 *
 * Basically a copy of section 6 of the data sheet of the LSM9DS1-sensor.
 *
 *  Created on: 03.06.2021
 *      Author: Cedric Boes
 */
#include "lsm9ds1_reg.h"
#include "registers.h"
#include "../../utils.h"

Register LSM9DS1_GXL_REGS::ACT_THS(0x04, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::ACT_DUR(0x05, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::INT_GEN_CFG_XL(0x06, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_X_XL(0x07, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Y_XL(0x08, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Z_XL(0x09, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_DUR_XL(0x0A, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::REFERENCE_G(0x0B, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::INT1_CTRL(0x0C, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_CTRL(0x0D, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::WHO_AM_I_GXL(0x0F, REGISTER_ACCESS::READ_ONLY, 0b01101000);

Register LSM9DS1_GXL_REGS::CTRL_REG1_G(0x10, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::CTRL_REG2_G(0x11, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::CTRL_REG3_G(0x12, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::ORIENT_CFG_G(0x13, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_SRC_G(0x14, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::OUT_TEMP_L(0x15, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_TEMP_H(0x16, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::STATUS_REG_G(0x17, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::OUT_X_G_L(0x18, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_X_G_H(0x19, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Y_G_L(0x1A, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Y_G_H(0x1B, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Z_G_L(0x1C, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Z_G_H(0x1D, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::CTRL_REG4(0x1E, REGISTER_ACCESS::READ_WRITE, 0b00111000);
Register LSM9DS1_GXL_REGS::CTRL_REG5_XL(0x1F, REGISTER_ACCESS::READ_WRITE, 0b00111000);
Register LSM9DS1_GXL_REGS::CTRL_REG6_XL(0x20, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::CTRL_REG7_XL(0x21, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::CTRL_REG8(0x22, REGISTER_ACCESS::READ_WRITE, 0b00000100);
Register LSM9DS1_GXL_REGS::CTRL_REG9(0x23, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::CTRL_REG10(0x24, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_GXL_REGS::INT_GEN_SRC_XL(0x26, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::STATUS_REG_XL(0x27, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::OUT_X_XL_L(0x28, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_X_XL_H(0x29, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Y_XL_L(0x2A, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Y_XL_H(0x2B, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Z_XL_L(0x2C, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_GXL_REGS::OUT_Z_XL_H(0x2D, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::FIFO_CTRL(0x2E, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::FIFO_SRC(0x2F, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_GXL_REGS::INT_GEN_CFG_G(0x30, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_X_G_H(0x31, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_X_G_L(0x32, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Y_G_H(0x33, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Y_G_L(0x34, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Z_G_H(0x35, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_THS_Z_G_L(0x36, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_GXL_REGS::INT_GEN_DUR_G(0x37, REGISTER_ACCESS::READ_WRITE, 0);

Register *LSM9DS1_GXL_REGS::USED_GXL[] = {
		&LSM9DS1_GXL_REGS::ACT_THS,
		&LSM9DS1_GXL_REGS::ACT_DUR,
		&LSM9DS1_GXL_REGS::INT_GEN_CFG_XL,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_X_XL,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Y_XL,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Z_XL,
		&LSM9DS1_GXL_REGS::INT_GEN_DUR_XL,
		&LSM9DS1_GXL_REGS::REFERENCE_G,
		&LSM9DS1_GXL_REGS::INT1_CTRL,
		&LSM9DS1_GXL_REGS::INT_CTRL,

		&LSM9DS1_GXL_REGS::WHO_AM_I_GXL,
		&LSM9DS1_GXL_REGS::CTRL_REG1_G,
		&LSM9DS1_GXL_REGS::CTRL_REG2_G,
		&LSM9DS1_GXL_REGS::CTRL_REG3_G,
		&LSM9DS1_GXL_REGS::ORIENT_CFG_G,
		&LSM9DS1_GXL_REGS::INT_GEN_SRC_G,
		&LSM9DS1_GXL_REGS::OUT_TEMP_L,
		&LSM9DS1_GXL_REGS::OUT_TEMP_H,
		&LSM9DS1_GXL_REGS::STATUS_REG_G,
		&LSM9DS1_GXL_REGS::OUT_X_G_L,
		&LSM9DS1_GXL_REGS::OUT_X_G_H,
		&LSM9DS1_GXL_REGS::OUT_Y_G_L,
		&LSM9DS1_GXL_REGS::OUT_Y_G_H,
		&LSM9DS1_GXL_REGS::OUT_Z_G_L,
		&LSM9DS1_GXL_REGS::OUT_Z_G_H,
		&LSM9DS1_GXL_REGS::CTRL_REG4,
		&LSM9DS1_GXL_REGS::CTRL_REG5_XL,
		&LSM9DS1_GXL_REGS::CTRL_REG6_XL,
		&LSM9DS1_GXL_REGS::CTRL_REG7_XL,
		&LSM9DS1_GXL_REGS::CTRL_REG8,
		&LSM9DS1_GXL_REGS::CTRL_REG9,
		&LSM9DS1_GXL_REGS::CTRL_REG10,

		&LSM9DS1_GXL_REGS::INT_GEN_SRC_XL,
		&LSM9DS1_GXL_REGS::STATUS_REG_XL,
		&LSM9DS1_GXL_REGS::OUT_X_XL_L,
		&LSM9DS1_GXL_REGS::OUT_X_XL_H,
		&LSM9DS1_GXL_REGS::OUT_Y_XL_L,
		&LSM9DS1_GXL_REGS::OUT_Y_XL_H,
		&LSM9DS1_GXL_REGS::OUT_Z_XL_L,
		&LSM9DS1_GXL_REGS::OUT_Z_XL_H,
		&LSM9DS1_GXL_REGS::FIFO_CTRL,
		&LSM9DS1_GXL_REGS::FIFO_SRC,
		&LSM9DS1_GXL_REGS::INT_GEN_CFG_G,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_X_G_H,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_X_G_L,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Y_G_H,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Y_G_L,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Z_G_H,
		&LSM9DS1_GXL_REGS::INT_GEN_THS_Z_G_L,
		&LSM9DS1_GXL_REGS::INT_GEN_DUR_G,

		NULL
};

size_t LSM9DS1_GXL_REGS::SIZE_GXL = UTILS::arrayLength(const_cast<const Register**>(LSM9DS1_GXL_REGS::USED_GXL));


Register LSM9DS1_M_REGS::OFFSET_X_REG_M_L(0x05, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::OFFSET_X_REG_M_H(0x06, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::OFFSET_Y_REG_M_L(0x07, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::OFFSET_Y_REG_M_H(0x08, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::OFFSET_Z_REG_M_L(0x09, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::OFFSET_Z_REG_M_H(0x0A, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_M_REGS::WHO_AM_I_M(0x0F, REGISTER_ACCESS::READ_ONLY, 0b00111101);

Register LSM9DS1_M_REGS::CTRL_REG1_M(0x20, REGISTER_ACCESS::READ_WRITE, 0b00010000);
Register LSM9DS1_M_REGS::CTRL_REG2_M(0x21, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::CTRL_REG3_M(0x22, REGISTER_ACCESS::READ_WRITE, 0b00000011);
Register LSM9DS1_M_REGS::CTRL_REG4_M(0x23, REGISTER_ACCESS::READ_WRITE, 0);
Register LSM9DS1_M_REGS::CTRL_REG5_M(0x24, REGISTER_ACCESS::READ_WRITE, 0);

Register LSM9DS1_M_REGS::STATUS_REG_M(0x27, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_M_REGS::OUT_X_M_L(0x28, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_M_REGS::OUT_X_M_H(0x29, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_M_REGS::OUT_Y_M_L(0x2A, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_M_REGS::OUT_Y_M_H(0x2B, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_M_REGS::OUT_Z_M_L(0x2C, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);
Register LSM9DS1_M_REGS::OUT_Z_M_H(0x2D, REGISTER_ACCESS::READ_ONLY, NO_DEFAULT_VALUE);

Register LSM9DS1_M_REGS::INT_CFG_M(0x30, REGISTER_ACCESS::READ_WRITE, 0b00001000);
Register LSM9DS1_M_REGS::INT_SRC_M(0x31, REGISTER_ACCESS::READ_ONLY, 0);
Register LSM9DS1_M_REGS::INT_THS_M_L(0x32, REGISTER_ACCESS::READ_ONLY, 0);
Register LSM9DS1_M_REGS::INT_THS_M_H(0x33, REGISTER_ACCESS::READ_ONLY, 0);

Register *LSM9DS1_M_REGS::USED_M[] = {
		&LSM9DS1_M_REGS::OFFSET_X_REG_M_L,
		&LSM9DS1_M_REGS::OFFSET_X_REG_M_H,
		&LSM9DS1_M_REGS::OFFSET_Y_REG_M_L,
		&LSM9DS1_M_REGS::OFFSET_Y_REG_M_H,
		&LSM9DS1_M_REGS::OFFSET_Z_REG_M_L,
		&LSM9DS1_M_REGS::OFFSET_Z_REG_M_H,

		&LSM9DS1_M_REGS::WHO_AM_I_M,

		&LSM9DS1_M_REGS::CTRL_REG1_M,
		&LSM9DS1_M_REGS::CTRL_REG2_M,
		&LSM9DS1_M_REGS::CTRL_REG3_M,
		&LSM9DS1_M_REGS::CTRL_REG4_M,
		&LSM9DS1_M_REGS::CTRL_REG5_M,

		&LSM9DS1_M_REGS::STATUS_REG_M,
		&LSM9DS1_M_REGS::OUT_X_M_L,
		&LSM9DS1_M_REGS::OUT_X_M_H,
		&LSM9DS1_M_REGS::OUT_Y_M_L,
		&LSM9DS1_M_REGS::OUT_Y_M_H,
		&LSM9DS1_M_REGS::OUT_Z_M_L,
		&LSM9DS1_M_REGS::OUT_Z_M_H,

		&LSM9DS1_M_REGS::INT_CFG_M,
		&LSM9DS1_M_REGS::INT_SRC_M,
		&LSM9DS1_M_REGS::INT_THS_M_L,
		&LSM9DS1_M_REGS::INT_THS_M_H,

		NULL
};

size_t LSM9DS1_M_REGS::SIZE_M = UTILS::arrayLength(const_cast<const Register**>(LSM9DS1_M_REGS::USED_M));
